### ISSUE TITLE
Implement remote Youtube live streaming management

### ISSUE THREAD

**Issue by jesselloyd** [jesselloyd/carthage-coc#1]
The user wants to be able to live stream sermons and archived them in a cost efficient way. Youtube has been selected as the platform for content delivery and storage.

- [ ] **Allow administrators to start and stop live streaming in the Administrator Dashboard**
- [ ] **Allow administrators to start and stop live streaming in the Sermon view**
- [ ] **Allow administrators to configure the Youtube channel used for live streaming in the Administrator Dashboard**
- [ ] **Retrieve and display a list of previous sermons from the church Youtube channel in the Sermon view**
- [x] **Allow any user to view an ongoing live stream in the Sermon view**
- [ ] **Allow any user to view and search for previous sermons in the Sermon view**
- [ ] **Allow registered users to view and comment on sermons in the Sermon view**
- [ ] **Allow administrators to moderate comments and add search tags to sermons to aid in making sermons searchable**
- [x] **Use modestbranding=1 in live stream embedded video** (regular site visitors may be discouraged by Youtube. This demographic is older church members who may view Youtube negatively (undeservedly))
