### ISSUE TITLE
Implement church directory service

### ISSUE THREAD

**Issue by jesselloyd** [jesselloyd/carthage-coc#2]
The user wants to be able to members to be able to register for an account and add their details to a private church directory. Users are to be manually approved by administrators to gain access to the church directory. 

- [x] Allow visitors to register for the site with the following fields in the Sign up view:
    - [x] First name
    - [x] Last name
    - [x] Email
    - [x] Password
    - [x] Confirm password
    - [x] Address
    - [x] State
    - [x] Zip code
    - [x] Phone number
    - [x] Profile picture

- [ ] Allow administrators to view, create and edit a list of registered users, split by the following categories in the Admin view and the Admin Dashboard:
    - [ ] Active
    - [ ] Pending

- [ ] Allow registered users to browse and search the church directory in the Directory view
    - [x] Present a list of search suggestions as the user types
    - [x] Show a count of search results
    - [ ] Paginate or infinite scroll search results
